language: cpp
compiler: gcc
dist: trusty
script: 
  - cd optional_files
  - cd project
  - make config=testing_x64
  - cd ..
  - cd build
  - ./CAST_linux_x64_testing
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
after_success:
  - coveralls 
notifications:
  email: false
