language: cpp
compiler: gcc
dist: trusty
script: 
  - gcc --version
  - g++ --version
  - gcov --version
  - cd optional_files
  - cd project
  - make config=testing_x64
  - cd ..
  - cd build
  - ./CAST_linux_x64_testing
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
after_success:
  - cd ..
  - cd ..
  - gcov optional_files/project/obj/x64/Testing/*
  - coveralls --no-gcov --include src/
notifications:
  email: false
