language: cpp
compiler: gcc
dist: trusty
script: 
  - gcc --version
  - g++ --version
  - gcov --version
  - lcov --version
  - cd optional_files
  - cd project
  - make config=testing_x64
  - cd ..
  - cd build
  - ./CAST_linux_x64_testing
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - sudo make -C lcov-1.13/ install  
  - gem install coveralls-lcov
after_success:
  - cd ..
  - cd project/obj/x64/Testing
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --remove coverage.info '/home/travis/build/AKEngels/CAST/submodules/*' --output-file coverage.info
  - lcov --remove coverage.info '/home/travis/build/AKEngels/CAST/src/gtest/*' --output-file coverage.info 
  - lcov --list coverage.info
  - coveralls-lcov coverage.info
notifications:
  email: false
