language: cpp
compiler: gcc
script:     # this is what is tested: commands that are also needed on a "normal" computer
  - cd optional_files                                      # go into folder optional_files
  - premake5 gmake                                         # run premake to create CAST makefile
  - cd project                                             # go into project folder
  - make config=testing_x64                                # create CAST testing configuration
  - cd ../build                                            # go into build folder
  - ./CAST_linux_x64_testing                               # run CAST (testing configuration)
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # add repo with compiler g++-5
  - sudo apt-get update -qq                                # update package list (-qq = do that very quiet)
install:
  - sudo apt-get install -qq g++-7                                              # install g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90       # set g++ to g++-5 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90       # set gcc to gcc-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90    # set gcov to gcov-5

  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz # get lcov from debian sources
  - tar xf lcov_1.13.orig.tar.gz                                                # unpack lcov
  - sudo make -C lcov-1.13/ install                                             # install lcov
  - gem install coveralls-lcov                                                  # install coveralls-lcov
  
  - cd submodules/boost                                                         # go into boost folder
  - ./bootstrap.sh                                                              # run bootstrap
  - ./b2 headers                                                                # build boost headers
  - cd ../..                                                                    # go back to main CAST folder
  
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz # get premake5 alpha
  - tar xf premake-5.0.0-alpha14-linux.tar.gz                                   # untar premake5
  - sudo install premake5 /usr/local/bin                                        # install premake5
after_success:
  - cd ../project/obj/x64/Testing                                               # go into folder with object files 
  - lcov --capture --directory . --output-file coverage.info                    # create coverage.info file
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info            # remove standard library from coverage.info 
  - lcov --remove coverage.info '/home/travis/build/AKEngels/CAST/submodules/*' --output-file coverage.info # remove submodules
  - lcov --remove coverage.info '/home/travis/build/AKEngels/CAST/src/Tests/*' --output-file coverage.info  # remove sourcecode for tests 
  - lcov --list coverage.info                                                   # show coverage information in terminal
  - coveralls-lcov coverage.info                                                # send coverage information to coveralls.io
notifications:
  email: false    # don't send emails
