#ifndef CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ALLINTERNALCOORDINATES_H_
#define CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ALLINTERNALCOORDINATES_H_

#include"BondDistance.h"
#include"BondAngle.h"
#include"DihedralAngle.h"
#include"Translations.h"
#include"Rotations.h"

#endif // CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ALLINTERNALCOORDINATES_H_