#ifndef CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ROTATORLISTENER_H_
#define CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ROTATORLISTENER_H_

namespace internals{

class RotatorListener {
public:
	virtual void setAllFlag() = 0;
};

}

#endif // CAST_INTERNALCOORDINATES_INTERNALCOORDINATES_ROTATORLISTENER_H_
